### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by bergjs** [per-gron/emiflake#4]
Hi,

hope you guys can help me. I tried to re-build a project I haven't touched in a while and I get an error when trying to install emiflake:

```
> emiflake@1.1.1 preinstall /Users/Jonas/Documents/Entwicklung/dowser/pro/api/node_modules/.staging/emiflake-a5d1c4eb0f6749b004251d1e25495e26
> node-gyp configure build

  CXX(target) Release/obj.target/emiflake/src/flake.o
  CXX(target) Release/obj.target/emiflake/src/module.o
In file included from ../src/module.cc:5:
../src/EmiFlake.h:12:31: error: expected class name
class EmiFlake : public node::ObjectWrap {
                              ^
../src/EmiFlake.h:31:51: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> ByteLength(const v8::Arguments& args);
                                                  ^~~~~~~~~~~~~
                                                  v8::internal::Arguments
/Users/Jonas/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cc:5:
../src/EmiFlake.h:32:50: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> BitLength(const v8::Arguments& args);
                                                 ^~~~~~~~~~~~~
                                                 v8::internal::Arguments
/Users/Jonas/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cc:5:
../src/EmiFlake.h:33:49: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Generate(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/Jonas/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/module.cc:5:
../src/EmiFlake.h:34:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/Jonas/.node-gyp/4.1.1/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/module.cc:12:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/Jonas/.node-gyp/4.1.1/include/node/v8.h:885:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
6 errors generated.
make: *** [Release/obj.target/emiflake/src/module.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/Jonas/Documents/Entwicklung/dowser/pro/api/node_modules/.staging/emiflake-a5d1c4eb0f6749b004251d1e25495e26
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
core-util-is@1.0.2 node_modules/mongoose/node_modules/mongodb/node_modules/readable-stream/node_modules/core-util-is -> node_modules/core-util-is
inherits@2.0.1 node_modules/mongoose/node_modules/mongodb/node_modules/readable-stream/node_modules/inherits -> node_modules/inherits
isarray@0.0.1 node_modules/mongoose/node_modules/mongodb/node_modules/readable-stream/node_modules/isarray -> node_modules/isarray
process-nextick-args@1.0.3 node_modules/mongoose/node_modules/mongodb/node_modules/readable-stream/node_modules/process-nextick-args -> node_modules/process-nextick-args
string_decoder@0.10.31 node_modules/mongoose/node_modules/mongodb/node_modules/readable-stream/node_modules/string_decoder -> node_modules/string_decoder
util-deprecate@1.0.2 node_modules/mongoose/node_modules/mongodb/node_modules/readable-stream/node_modules/util-deprecate -> node_modules/util-deprecate
dowser@1.1.4 /Users/Jonas/Documents/Entwicklung/dowser/pro/api
└─┬ bcrypt@0.7.8 
  └── bindings@1.0.0 

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.4.1
npm ERR! code ELIFECYCLE

npm ERR! emiflake@1.1.1 preinstall: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the emiflake@1.1.1 preinstall script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the emiflake package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls emiflake
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jonas/Documents/Entwicklung/dowser/pro/api/npm-debug.log
```

I tried all kinds of stuff already, including updating npm, but no luck :(

**Comment by bergjs** [comment]
figured it out, I had to use an older version of node. I used the node version manager 'n' to switch to 0.10.38 and now it works
